config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {  registrations: 'users/registrations'}
  resources :libraries
  resources :issuers
  resources :admins
  resources :managers
  resources :books
  resources :book_histories,only:[:destroy]

  get  '/search_book/',to:"books#search_book",as: 'search_book'
  post '/books/:id/issue_book',to:'books#issue_book',as: 'issue_book'
  post '/books/:id/issue_book_request',to:'books#issue_book_request',as: 'issue_book_request'
  post '/books/:id/return_book',to:'books#return_book',as: 'return_book'
  post '/managers/:id/change_status',to:'managers#change_status',as:'manager_change_status'
  post '/issuers/:id/change_status',to:'issuers#change_status',as:'issuer_change_status'
  post '/books/:id/change_status',to:'books#change_status',as:'book_change_status'
  post '/issuers/:id/approve',to:'issuers#approve',as:'issuer_approval'

  root 'libraries#index'
end

app/models/issuer.rb
class Issuer < User
  has_one_attached :image
  has_many :book_histories

  enum status:[:active , :inactive]

  validates :status,:fname,:lname,:balance, presence: true
  validates :status, inclusion: {in: %w(active inactive)}
  validates :balance, numericality: {only_integer: true , greater_than_or_equal_to: 0}
  validates :fname,:lname, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/controllers/issuers_controller.rb
class IssuersController < ApplicationController
 before_action :check_sign_in
 before_action :find_issuer,only:[:edit,:destroy,:show,:change_status]

  def index
    @issuers = Issuer.where(library_id: current_user.library_id,approval:'approved').order('created_at ASC')
  end

  def show
    if current_user.type=="Admin"
      @history=BookHistory.where(issuer_id: @issuer_id,end_date:[nil,false])
    end
    @issued_books=BookHistory.where(issuer_id:@issuer.id,end_date: nil).where.not(start_date: nil)
    @fine=Library.find(@issuer.library_id).fine
    @books=Book.where(library_id:@issuer.library_id)
  end

  def edit
  end

  def update
    if Issuer.update(params[:id],parameters)
      redirect_to issuers_path
    else
      render 'edit'
    end
  end

  def destroy
    @issuer.destroy
    redirect_to issuers_path
  end

  def change_status
    if @issuer.active?
      @issuer.update(status:'inactive')
    else
      @issuer.update(status:'active')
    end
    redirect_to issuers_path
  end

  def approve
    @issuer=Issuer.find(params[:id])
    if @issuer.unapproved?
      @issuer.update(approval:'approved')
      IssuerMailer.welcome(@issuer).deliver_now!
    end
    redirect_to root_path
  end

private

  def check_sign_in
    if !current_user
      redirect_to libraries_path
    end
  end

  def find_issuer
    @issuer=Issuer.find(params[:id])
  end

  def parameters
    params.require(:issuer).permit(:email,:password,:image,:fname,:lname,:balance,:status)
  end
end

app/views/issuers/edit.html.erb
<div class="jumbotron container col-md-3">
  <h1 class="text-center">Edit Issuer</h1>
  <%= form_for @issuer,validate: true do |f|%>
    <div class="form-group">
      <%= f.label :email%>
      <%= f.text_field :email,class:"form-control" ,required:true%>
    </div>
    <div class="form-group">
      <%= f.label "First Name"%>
      <%= f.text_field :fname,class:"form-control",required:true%>
    </div>
    <div class="form-group">
      <%= f.label "Last Name"%>
      <%= f.text_field :lname,class:"form-control",required:true%>
    </div>
    <div class="form-group">
      <%= f.label :balance%>
      <%= f.number_field :balance,class:"form-control",required:true%>
    </div>
    <div class="form-group">
      <%= f.label :image%>
      <%= f.file_field :image,class:"form-control",required:true%>
    </div>
    <div class="form-group">
      <%= f.label :status%>
      <%= f.select(:status,options_for_select([['Active','active'],['Inactive','inactive']]),{},class:"form-control")%>
    </div>
    <%= f.submit "Update",class:"btn btn-primary"%>
  <%end%>
</div>

app/views/issuers/index.html.erb
<h1 class="text-center">Issuers of Library <%= current_user.library_id%></h1>
<% i=0%>
<div class="container">
  <% @issuers.each do |issuer| %>
    <%if i%3==0 %>
      <div class="row ">
    <%end%>
      <div class=" text-center col-md-3">
        <div class="card" style="width: 18rem;">
          <% if issuer.image%>
            <%=  image_tag issuer.image , size: '200x200',class:"card-img-top"%>
          <%end%>
          <div class="card-body">
            <h5 class="card-title"><%= issuer.fname + " " + issuer.lname %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Status: <%= issuer.status.capitalize %></li>
            <li class="list-group-item">Balance: <%= issuer.balance %></li>
            <%if current_user.type=="Admin"%>
              <li class="list-group-item"><%= link_to 'Change Status', issuer_change_status_path(issuer),method: :post,class:"card-link" %></li>
            <%end%>
            <li class="list-group-item"><%= link_to "View Profile",issuer_path(issuer),class:"card-link"%></li>
          </ul>
          <div class="card-body">
            <%if current_user.type=="Admin"%>
              <%= link_to "Edit",edit_issuer_path(issuer),class:"card-link"%>
              <%= link_to "Delete",issuer_path(issuer),data:{confirm:"Are you sure?"},method: :delete,class:"card-link"%>
            <%end%>
          </div>
        </div>
      </div>
      <div class="col-sm-1"></div>
    <% i+=1 %>
    <%if i%3==0 %>
      </div>
    <%end%>
    <br>
  <%end%>
</div>

app/views/issuers/show.html.erb
<% if current_user.type=="Issuer"%>
  <h1 class="text-center">Welcome <%= @issuer.fname+" "+@issuer.lname %> to  Dashboard</h1>
<%else%>
  <h1 class="text-center"> <%= @issuer.fname+" "+@issuer.lname %></h1>
<%end%>
<div class="row">
  <div class="col col-md-1"></div>
  <div class="col col-md-4">
    <table class="text-center table table-striped table-bordered">
      <tr><th class="bg-secondary " colspan="2">Details</th></tr>
      <tr>
        <td>Email</td>
        <td><%= @issuer.email%></td>
      </tr>
      <tr>
        <td>First Name</td>
        <td><%= @issuer.fname%></td>
      </tr>
      <tr>
        <td>Last Name</td>
        <td><%= @issuer.lname%></td>
      </tr>
      <tr>
        <td>Balance</td>
        <td><%= @issuer.balance%></td>
      </tr>
    </table>
  </div>
  <div class="col col-md-3"></div>
  <div class="col col-md-2">
    <% if @issuer.image.attached? %>
      <%= image_tag @issuer.image, size:"200x220",class:"rounded" %>
    <% end %>
  </div>
</div>

<% if @issued_books %>
  <div class="container">
    <h3 class="text-center">Issued Books</h3>
    <table class="table table-bordered table-hover">
      <tr class="bg-secondary"><th>Title</th><th>ISBN</th><th>Author</th><th>Year</th><th>Genre</th><th>Issued Date</th><th>Days</th><th>Fine</th>
        <%if current_user.type=="Issuer"%>
          <th>Return Book</th>
        <%end%>
      </tr>
      <% if @issued_books!=nil%>
        <% @issued_books.each do |hist| %>
          <tr>
          <% days = (Time.now - Time.parse(hist.start_date)).to_i/(3600*24)%>
          <% book=@books.where(id:hist.book_id).last %>
          <% if book!=nil %>
            <td><%= book.title %></td>
            <td><%= book.isbn %></td>
            <td><%= book.author %></td>
            <td><%= book.year %></td>
            <td><%= book.genre %></td>
            <td><%= hist.start_date %></td>
            <td><%= days%></td>
            <td><%= days>30 ?fin=(days-30)*@fine: fin=0  %></td>
            <%if current_user.type == "Issuer"%>
              <td><%= link_to "Return this book",return_book_path(book),method: :post,class:"btn btn-info" %></td>
            <%end%>
          <%end%>
          </tr>
        <%end%>
      <%end%>
    </table>
  </div>
<%end%>