config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {  registrations: 'users/registrations'}
  resources :libraries
  resources :issuers
  resources :admins
  resources :managers
  resources :books
  resources :book_histories,only:[:destroy]

  get  '/search_book/',to:"books#search_book",as: 'search_book'
  post '/books/:id/issue_book',to:'books#issue_book',as: 'issue_book'
  post '/books/:id/issue_book_request',to:'books#issue_book_request',as: 'issue_book_request'
  post '/books/:id/return_book',to:'books#return_book',as: 'return_book'
  post '/managers/:id/change_status',to:'managers#change_status',as:'manager_change_status'
  post '/issuers/:id/change_status',to:'issuers#change_status',as:'issuer_change_status'
  post '/books/:id/change_status',to:'books#change_status',as:'book_change_status'
  post '/issuers/:id/approve',to:'issuers#approve',as:'issuer_approval'

  root 'libraries#index'
end

app/models/manager.rb
class Manager < User
  belongs_to :library
  has_one_attached :image

  enum status:[:active , :inactive]

  validates :status ,presence: true
  validates :status, inclusion: {in: %w(active inactive)}
end

app/controllers/managers_controller.rb
class ManagersController<ApplicationController
  before_action :check_sign_in
  before_action :find_manager,only:[:show,:edit,:destroy,:change_status]

  def index
    @managers = Manager.where(library_id: current_user.library_id).order("created_at ASC")
  end

  def show
    @book=Book.last
    @book_request=BookHistory.where(start_date:nil)
  end

  def new
    @manager=Manager.new
  end

  def create
    fields=manager_params
    fields[:library_id]=current_user.library_id
    @manager=Manager.new(fields)
    if @manager.save
      redirect_to admin_path(current_user.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if Manager.update(manager_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @manager.destroy
    redirect_to managers_path
  end

  def change_status
    if @manager.active?
      @manager.update(status:'inactive')
    else
      @manager.update(status:'active')
    end
    redirect_to managers_path
  end

private

  def manager_params
    params.require(:manager).permit(:email,:status,:image)
  end

  def find_manager
    @manager=Manager.find(params[:id])
  end

  def check_sign_in
    if !current_user
      redirect_to libraries_path
    end
  end
end

app/views/managers/edit.html.erb
<div class="container col-md-3 pt-5">
  <h1 class="text-center">Edit Manager</h1>
  <%= form_for @manager,validate: true do |f|%>
    <div class="form-group">
      <%= f.text_field :email,class:"form-control",required:true%>
    </div>
    <div class="form-group">
      <%= f.file_field :image,class:"form-control btn btn-primary",required:true%>
    </div>
    <div class="form-group">
      <%= f.select(:status,options_for_select([['Active','active'],['Inactive','inactive']]),{},class:"form-control")%>
    </div>
    <%= f.submit "Update",class:"btn btn-primary"%>
  <%end%>
</div>

app/views/managers/index.html.erb
<h1 class="text-center">Managers</h1>
<% i=0%>
<div class="container">
  <% @managers.each do |manager| %>
    <%if i%3==0 %>
      <div class="row ">
    <%end%>
      <div class="text-center col-md-3">
        <div class="card" style="width: 18rem;">
          <% if manager.image%>
            <%=  image_tag manager.image , size: '200x200',class:"card-img-top"%>
          <%end%>
          <div class="card-body">
            <h6 class="card-title">Email: <%= manager.email %></h6>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Status: <%= manager.status.capitalize%></li>
            <li class="list-group-item">  <%= link_to 'Change Status', manager_change_status_path(manager),method: :post,class:"card-link" %></li>
          </ul>
          <div class="card-body">
            <%= link_to "Edit", edit_manager_path(manager),class:"card-link" %>
            <%= link_to "Delete",manager_path(manager),data:{confirm: "Do you really want to delete this?"},method: :delete,class:"card-link"%>
          </div>
        </div>
      </div>
      <div class="col-sm-1"></div>
    <% i+=1 %>
    <%if i%3==0 %>
      </div>
    <%end%>
    <br>
  <%end%>
</div>

app/views/managers/new.html.erb
<div class="container pt-5 jumbotron col-md-3">
  <h4 class="text-center ">Create New Manager</h2>
  <%= form_for @manager,validate: true do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true,required:true, autocomplete: "email",class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password,required:true, autocomplete: "new-password",class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation,required:true, autocomplete: "new-password",class:"form-control" %>
    </div>

    <div class="form-group">
    <%= f.file_field :image ,class:"btn btn-primary form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :status %>
      <%= f.select( :status , options_for_select([['Active','active'],['Inactive','inactive']]),{},{:class=>"form-control"})%>
    </div>
  <br>
    <div class="form-group text-center">
      <%= f.submit "Create",class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/managers/show.html.erb
<h1 class="text-center" >Welcome Manager</h1><br>
<div class="row text-center">
  <div class="col col-md-1"></div>
  <div class="col">
    <h2>Book Issue Request</h2>
    <table class="table table-bordered table-hover container text-center">
      <tr class="bg-secondary "><th>Issuer ID</th><th>Book ID</th><th>Approve</th><th>Reject</th></tr>
      <%@book_request.each do |book| %>
        <tr>
          <td><%= link_to book.issuer_id,issuer_path(book.issuer_id) %></td>
          <td><%= link_to book.book_id,book_path(book.book_id) %></td>
          <td><%= link_to "Approve Request",issue_book_path(book),method: :post %></td>
          <td><%= link_to "Reject Request",book_history_path(book),method: :delete %></td>
        </tr>
      <%end%>
    </table>
  </div>

  <div class="col">
    <% if @manager.image.attached? %>
        <%= image_tag @manager.image ,size:"200x220",class:"rounded"%>
    <% end %>
  </div>
</div>