config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {  registrations: 'users/registrations'}
  resources :libraries
  resources :issuers
  resources :admins
  resources :managers
  resources :books
  resources :book_histories,only:[:destroy]

  get  '/search_book/',to:"books#search_book",as: 'search_book'
  post '/books/:id/issue_book',to:'books#issue_book',as: 'issue_book'
  post '/books/:id/issue_book_request',to:'books#issue_book_request',as: 'issue_book_request'
  post '/books/:id/return_book',to:'books#return_book',as: 'return_book'
  post '/managers/:id/change_status',to:'managers#change_status',as:'manager_change_status'
  post '/issuers/:id/change_status',to:'issuers#change_status',as:'issuer_change_status'
  post '/books/:id/change_status',to:'books#change_status',as:'book_change_status'
  post '/issuers/:id/approve',to:'issuers#approve',as:'issuer_approval'

  root 'libraries#index'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library
  has_many_attached :images
  has_many :book_histories

  enum status:[:available,:unavailable]

  validates :title,:isbn,:author,:year,:genre,:no_of_copies,:status,:library_id,:images ,presence: true
  validates :isbn , length: { in: 10..13 }
  validates :year,  length: { is: 4 }
  validates :year,:isbn,:no_of_copies ,numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :isbn,uniqueness: true
  validates :status, inclusion: {in: %w(available unavailable)}
end

app/controllers/books_controller.rb
class BooksController<ApplicationController
  before_action :check_sign_in
  before_action :book_params,only:[:create]
  before_action :find_book,only:[:change_status,:show,:edit,:update,:destroy]

  def index
    @books = Book.where(library_id: current_user.library_id)
  end

  def new
    @book=Book.new
  end

  def create
    fields=book_params
    fields[:library_id]=current_user.library_id
    @book=Book.new(fields)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to current_user
  end

  def change_status
    if @book.available?
      @book.update(status:'unavailable')
    else
      @book.update(status:'available')
    end
    redirect_to books_path
  end

  def issue_book_request
    @book=Book.find(params[:id])
    if @book.unavailable?
      flash[:alert]="Sorry the book is not available :("
      redirect_to current_user
    elsif BookHistory.where(book_id:params[:id],issuer_id:current_user.id,end_date:nil).count>0
      flash[:alert]="You have already requested or issued this book!"
      redirect_to current_user
    else
      @history=BookHistory.create(book_id:@book.id,issuer_id:current_user.id)
      if @history.save
        current_user.book_histories << @history
        flash[:notice] = "You have successfully requested for a book!."
        redirect_to current_user
      else
        render 'show'
      end
    end
  end

  def issue_book
    @history=BookHistory.find(params[:id])
    if @history.update(start_date:Time.now.strftime("%d/%m/%Y").to_s)
      @issuer=Issuer.find(@history.issuer_id)
      @issuer.book_histories << @history
      flash[:notice] = "You have successfully issued book!."
      IssuerMailer.book_issue_success(@history.issuer_id,@history.book_id).deliver_now!
      redirect_to current_user
    else
      render 'show'
    end
  end

  def search_book
    @books=Book.where("LOWER(#{params[:search_key]}) LIKE LOWER(?)", "%#{params[:book][:title]}%")
  end

  def return_book
    @book=Book.find(params[:id])
    @history=BookHistory.where(book_id:params[:id],issuer_id:current_user.id)
    if @history.update(end_date:Time.now.strftime("%m/%d/%Y").to_s)
      flash[:notice] = "You have successfully returned book!."
      redirect_to current_user
    else
      render 'show'
    end
  end

private

  def check_sign_in
    if !current_user
      redirect_to libraries_path
    end
  end

  def find_book
    @book=Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title,:isbn,:status,:author,:year,:genre,:no_of_copies,images:[])
  end
end

app/views/books/_form.html.erb
<%= form_for @book,validate: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title  ,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :isbn %>
      <%= f.text_field :isbn  ,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author ,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :genre %>
      <%= f.text_field :genre ,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :no_of_copies %>
      <%= f.text_field :no_of_copies ,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :year %>
      <%= f.select :year, (Time.zone.now.year).downto(Time.zone.now.year-2000 ),{},class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :images %>
      <%= f.file_field :images,multiple:true,class:"form-control btn btn-primary" %>
    </div>

    <div class="form-group">
      <%= f.label :status %>
      <%= f.select( :status , options_for_select([['Available','available'],['Unavailable','unavailable']]),{},class:"form-control")%>
    </div>
    <div class="form-group text-center">
      <%= f.submit "Submit" ,class:"btn btn-primary" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<div class="container pt-3 jumbotron col-md-3">
  <h2 class="text-center">Edit Book</h2>
  <%= render 'form'%>
</div>

app/views/books/index.html.erb
<h1 class="text-center"><%= "Books of Library "+ current_user.library_id.to_s %></h1>
<% @books.each do |book| %>
  <div class="row container pt-5">
    <div class="col col-md-2"></div>
    <div class="text-center col col-md-4">

      <table class="table table-bordered table-striped">
        <tr ><td  colspan="2"><%= link_to book.title, book_path(book) %></td></tr>
        <tr>
          <td>ISBN</td> <td><%= book.isbn %></td>
        </tr>
        <tr>
          <td>Author</td> <td><%= book.author %></td>
        </tr>
        <tr>
          <td>Genre</td> <td><%= book.genre %></td>
        </tr>
        <tr>
          <td>Status</td> <td><%= book.status.capitalize %></td>
        </tr>
      </table>

      <% if current_user.type=="Manager"%>
        <%= link_to "Change Status", book_change_status_path(book),method: :post,class:"btn btn-info" %>
        <%= link_to "Edit", edit_book_path(book),class:"btn btn-primary" %>
        <%= link_to "Delete",book_path(book),data:{confirm: "Do you really want to delete this book?"},method: :delete,class:"btn btn-danger"%>
      <% elsif current_user.type=="Issuer"%>
        <%=link_to "Issue this book", issue_book_request_path(book), method: :post,class:"btn btn-success"%>
      <%end%>
    </div>
    <div class="col col-3"></div>
    <div class="col col-md-3">
      <% if book.images%>
        <%=  image_tag book.images[0] , size: '200x300'%>
      <%end%>
    </div>
  </div>
<%end%>

app/views/books/new.html.erb
<div class="container pt-3 jumbotron col-md-3">
  <h2 class="text-center">Create New Book</h2>
  <%= render 'form'%>
</div>

app/views/books/search_book.html.erb
<% if @books.count>0 %>
  <h1 class="text-center">Searched Books</h1>
  <table class="table  table-bordered table-hover container text-center">
    <tr class="bg-secondary"><th>ISBN</th><th>Title</th><th>Author</th><th>Year</th><th>No of Copies</th><th>Image</th><th>View Book</th></tr>
    <% @books.each do |book|%>
      <tr>
        <td><%=book.isbn%></td>
        <td><%=book.title%></td>
        <td><%=book.author%></td>
        <td><%=book.year%></td>
        <td><%=book.no_of_copies%></td>
        <td><%= image_tag book.images[0] ,size:'150x200'%></td>
        <td><%= link_to "View Book",book_path(book),class:"btn btn-primary"%></td>
      </tr>
    <%end%>
  </table>
<%else%>
  <div class="alert alert-danger text-center">No Books found!</div>
<%end%>

app/views/books/show.html.erb
<h1 class="text-center"><%= @book.title%></h1>
<div class="row">
  <div class="col col-md-1"></div>
  <div class="col col-md-2">
    <table class="table table-bordered table-hover text-center">
      <tr><th colspan="2" class="bg-secondary">Book Details</th></tr>
      <tr>
        <td>Title</td>
        <td><%= @book.title %></td>
      </tr>
      <tr>
        <td>ISBN</td>
        <td><%= @book.isbn %></td>
      </tr>
      <tr>
        <td>Author</td>
        <td><%= @book.author %></td>
      </tr>
      <tr>
        <td>Year</td>
        <td><%= @book.year %></td>
      </tr>
      <tr>
        <td>Genre</td>
        <td><%= @book.genre %></td>
      </tr>
      <tr>
        <td>No of Copies</td>
        <td><%= @book.no_of_copies %></td>
      </tr>
      <tr>
        <td>Status</td>
        <td><%= @book.status.capitalize %></td>
      </tr>
    </table>
  </div>
  <div class="col col-md-2"></div>
  <div class="col col-md-6">
    <% @book.images.each do |image|%>
    <%=  image_tag image , size: '200x200'%>
  <%end%>
  <br>
  <br>

  <%if current_user.type=="Issuer"%>
    <%= link_to "Issue Book",issue_book_request_path(@book),method: :post ,class:"btn btn-info"%>
  <% elsif current_user.type=="Manager"%>
    <%= link_to "Edit",edit_book_path(@book),class:"btn btn-primary" %>
    <%= link_to "Delete",book_path(@book),data:{confirm:"Do you really want to delete this book?"},method: :delete,class:"btn btn-danger" %>
  <%end%>
  </div>
</div>