config/routes.rb
Rails.application.routes.draw do

  devise_for :users ,controllers: {  registrations: 'users/registrations'}
  resources :libraries
  resources :issuers
  resources :admins
  resources :managers
  resources :books
  resources :book_histories,only:[:destroy]

  get  '/search_book/',to:"books#search_book",as: 'search_book'
  post '/books/:id/issue_book',to:'books#issue_book',as: 'issue_book'
  post '/books/:id/issue_book_request',to:'books#issue_book_request',as: 'issue_book_request'
  post '/books/:id/return_book',to:'books#return_book',as: 'return_book'
  post '/managers/:id/change_status',to:'managers#change_status',as:'manager_change_status'
  post '/issuers/:id/change_status',to:'issuers#change_status',as:'issuer_change_status'
  post '/books/:id/change_status',to:'books#change_status',as:'book_change_status'
  post '/issuers/:id/approve',to:'issuers#approve',as:'issuer_approval'

  root 'libraries#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg  navbar-light bg-light">
  <%= link_to "Libraries",libraries_path,class:"navbar-brand"%>
  <div class="collapse navbar-collapse ">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item">
        <%= link_to "Home",current_user,class:"nav-link"%>
      </li>

      <% if current_user.type=="Admin"%>
          <li class="nav-item">
            <%= link_to "Managers",managers_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Issuers",issuers_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
             <%= link_to "Change Fine Amount", edit_library_path(id: current_user.library_id),class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Create New Manager" , new_manager_path ,class:"nav-link" %>
          </li>
          <li class="nav-item ">
            <%= link_to 'Sign Out' , destroy_user_session_path , method: :delete,class:"btn btn-danger text-light nav-link"%>
          </li>
        </ul>
      <%else%>
          <li class="nav-item">
            <%= link_to "View Books",books_path,class:"nav-link"%>
          </li>
          <%if current_user.type=="Manager"%>
            <li>
              <%= link_to 'Create new Book', new_book_path ,class:"nav-link"%>
            </li>
          <%end%>
          <li class="nav-item">
            <%= link_to "Sign Out",destroy_user_session_path, method: :delete,class:"btn btn-danger text-light nav-link"%>
          </li>
        </ul>
        <%= form_for :book, url:search_book_path,method:'get',html: {class: 'form-inline my-0 my-lg-0'} do |f| %>
          <div class="input-group">
              <%= select_tag :search_key,options_for_select([['Author','Author'],['ISBN','ISBN'],['Title','title']]),class:"form-control my-0 my-sm-0 col-md-3"%>
              <%= f.text_field :title,placeholder:"Search Book" ,class:"form-control mr-sm-0" %>
              <div class="input-group-append">
                 <%= f.submit "Search" ,class:"btn btn-outline-success my-0 my-sm-0" %>
              </div>
          </div>
        <%end%>
      <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" if current_user%>
    <%if notice %>
      <p class="alert alert-success text-center"><%= notice %></p>
    <%end%>
    <%if alert %>
      <p class="alert alert-danger text-center"><%= alert %></p>
    <%end%>
    <%= yield %>
  </body>
</html>